services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    environment:
      SPRING_MONGODB_URI: mongodb://mongo:27017/church_operations
      CHURCH_NAME: Capstone Presbyterian Church
      CHURCH_ADDRESS: 111 Cactus Ave, North York, ON M2R 2V1
      CHURCH_CONTACT_INFO: lovecapstone@gmail.com
      CHURCH_TREASURER_NAME: Treasurer
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_SMTP_AUTH: "false"
      MAIL_SMTP_STARTTLS: "false"
      PASSWORD_RESET_FRONTEND_BASE_URL: http://localhost:5173
      PASSWORD_RESET_FROM_ADDRESS: no-reply@church.local
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
