package com.church.operation.util;

public enum SystemAuditOperation {
    FULL_BACKUP,
    FULL_RESTORE_VALIDATE,
    FULL_RESTORE_SAFETY_BACKUP,
    FULL_RESTORE_EXECUTE,
    FISCAL_ARCHIVE,
    FISCAL_CLEAN,
    FISCAL_RESTORE_VALIDATE,
    FISCAL_RESTORE_EXECUTE,
    TAX_RECEIPT_ISSUE,
    TAX_RECEIPT_ISSUE_BATCH,
    TAX_RECEIPT_VOID,
    TAX_RECEIPT_REPLACE,
    MEMBER_DELETE,
    REFERENCE_DATA_DELETE
}
