package com.church.operation.util;

public enum SystemAuditOperation {
    FULL_BACKUP,
    FULL_RESTORE_VALIDATE,
    FULL_RESTORE_SAFETY_BACKUP,
    FULL_RESTORE_EXECUTE,
    FISCAL_ARCHIVE,
    FISCAL_CLEAN,
    FISCAL_RESTORE_VALIDATE,
    FISCAL_RESTORE_EXECUTE,
    TAX_RECEIPT_ISSUE,
    TAX_RECEIPT_ISSUE_BATCH,
    TAX_RECEIPT_VOID,
    TAX_RECEIPT_REPLACE,
    YEAR_END_CLOSE,
    YEAR_END_REOPEN,
    MEMBER_DELETE,
    REFERENCE_DATA_DELETE,
    EMAIL_SETTINGS_TEST,
    EMAIL_SETTINGS_UPDATE,
    EMAIL_SETTINGS_RESET,
    CHURCH_SETTINGS_UPDATE,
    CHURCH_SETTINGS_RESET
}
